---
version: '1'

services:
  webserver:
    image: apache/airflow:latest-python3.12
    entrypoint: ['/opt/airflow/script/entrypoint.sh']
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Sequential
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/creds/cred.json
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/output
      - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./creds:/opt/airflow/creds
    ports:
      - "8080:8080"
    healthcheck:
      test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: apache/airflow:latest-python3.12
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/output
      - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./creds:/opt/airflow/creds
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Sequential
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/creds/cred.json
    command: bash -c "pip install -r ./requirements.txt && airflow db upgrade && airflow scheduler"
    #command: bash -c "airflow db upgrade && airflow scheduler"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
